typography_spectrum: 0.43267231597565114
color:
  saturation: 0.9843469429761171
  brandStrength: 0.11570419860072434
  lightness: 0.13849028130061924
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  rhythmicContrast: 0.7691114449407905
layout_spectrum: 0.5747946610208601
name: Kyle Hermsen
navigation:
  - name: Demo Reel
    id: ab6378d3-3ed3-45e9-8b1f-0887f341dc2b
    type: content
  - name: About Me
    id: ad890adc-e7be-408b-9023-f18de6e7ff83
    type: content
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Explore. Create.
description: Cinematographer•Photographer•Husband•Father
